id: AD48C5B0C
title: 'Bestower of Supreme Twofold Attainment: A Prayer to the Great Fifteenth Karmapa'
type: translation
pechas:
- I4BB762E2
- IF4FC84B5
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:32.966690
  last_modified_at: 2023-01-04 11:51:32.966719
  collections:
  - Fifteenth Karmapa Series
  - Works of Tibetan Masters
alignment_to_base:
  I4BB762E2/B1DF: 336A
  IF4FC84B5/F669: 336A
